// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: Sqrt/proto/sqrt.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetSQRTClient is the client API for GetSQRT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetSQRTClient interface {
	SQRT(ctx context.Context, in *NumRequest, opts ...grpc.CallOption) (*NumRespone, error)
}

type getSQRTClient struct {
	cc grpc.ClientConnInterface
}

func NewGetSQRTClient(cc grpc.ClientConnInterface) GetSQRTClient {
	return &getSQRTClient{cc}
}

func (c *getSQRTClient) SQRT(ctx context.Context, in *NumRequest, opts ...grpc.CallOption) (*NumRespone, error) {
	out := new(NumRespone)
	err := c.cc.Invoke(ctx, "/grpc.GetSQRT/SQRT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSQRTServer is the server API for GetSQRT service.
// All implementations must embed UnimplementedGetSQRTServer
// for forward compatibility
type GetSQRTServer interface {
	SQRT(context.Context, *NumRequest) (*NumRespone, error)
	mustEmbedUnimplementedGetSQRTServer()
}

// UnimplementedGetSQRTServer must be embedded to have forward compatible implementations.
type UnimplementedGetSQRTServer struct {
}

func (UnimplementedGetSQRTServer) SQRT(context.Context, *NumRequest) (*NumRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SQRT not implemented")
}
func (UnimplementedGetSQRTServer) mustEmbedUnimplementedGetSQRTServer() {}

// UnsafeGetSQRTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetSQRTServer will
// result in compilation errors.
type UnsafeGetSQRTServer interface {
	mustEmbedUnimplementedGetSQRTServer()
}

func RegisterGetSQRTServer(s grpc.ServiceRegistrar, srv GetSQRTServer) {
	s.RegisterService(&GetSQRT_ServiceDesc, srv)
}

func _GetSQRT_SQRT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetSQRTServer).SQRT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GetSQRT/SQRT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetSQRTServer).SQRT(ctx, req.(*NumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetSQRT_ServiceDesc is the grpc.ServiceDesc for GetSQRT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetSQRT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.GetSQRT",
	HandlerType: (*GetSQRTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SQRT",
			Handler:    _GetSQRT_SQRT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Sqrt/proto/sqrt.proto",
}
